Feature/#11 회원가입 API
almondiz/almondiz-server pull request #13
Opened 2022-08-24 10:17 UTC by coderclcl

## 개요 ✋
회원가입 API 구현 

## 작업사항 🗒️
User CRUD rest api 구현 완료 
- 회원가입 
- 회원 탈퇴
- 회원 정보 조회
- 모든 회원 조회 
- 회원 정보 수정 
- swagger 적용 
- swagger 테스트는 post 제외하고 모두 완료되었습니다. 
- User의 nickName 조회 관련 tag, nut entity, controller, service 구현 
- User의 profile img 조회 관련 profileFile entity, controller, service 구현 

## 논의 필요한 사항 

## 변경로직 🛠️

closes #11

2022-08-27 08:25 UTC, yejipractice commented on src/main/java/org/almondiz/almondiz/user/dto/UserResponseDto.java
> +        // 다른 테이블에서 조회하는 방법으로 수정 필요 - dto에서 조회하는게 맞는가?
서비스에서 조회하고 인자로 넣어주는 식으로 해야합니다!

2022-08-27 08:27 UTC, yejipractice commented on src/main/java/org/almondiz/almondiz/user/dto/UserRegisterDto.java
> +     private Long userId;
userId는 가입하면 디비에서 자동으로 생성될 거라서 클라이언트가 userId를 아직 모르는 상태고 대신에 이메일을 받으면 될 것 같아요!

2022-08-27 08:31 UTC, yejipractice requested changes
고생하셨어요!! 훨씬 좋아보여요~~ 최고최고👍

2022-08-27 08:31 UTC, yejipractice commented on src/main/java/org/almondiz/almondiz/user/UserService.java
> +    public User signup(UserRegisterDto userRegisterDto){
아래 email을 Id대신 할 거라고 작성드린 점처럼 여기서도 id대신 email로 하면 될 것 같아요

2022-08-27 08:31 UTC, yejipractice commented on src/main/java/org/almondiz/almondiz/user/UserService.java
> +    public User signup(UserRegisterDto userRegisterDto){
그리고 repo관련된 로직들에는 트랜잭션 어노테이션을 다 붙이는 게 좋다고 알고 있어요..!단순히 조회하는 기능이라고 하더라도 .. @Transaction입니다!

2022-08-27 08:31 UTC, yejipractice commented on src/main/java/org/almondiz/almondiz/user/UserService.java
> +    public List<User> getAllUsers(){
이 메소드는 dto 적용 안하시는 건가요?-?

2022-08-28 07:49 UTC, coderclcl commented on src/main/java/org/almondiz/almondiz/user/dto/UserResponseDto.java
> +        // 다른 테이블에서 조회하는 방법으로 수정 필요 - dto에서 조회하는게 맞는가?
넵~ 같이 고민해주셔서 감사합니다!

2022-08-28 07:49 UTC, coderclcl commented on src/main/java/org/almondiz/almondiz/user/dto/UserRegisterDto.java
> +     private Long userId;
아아 그렇군요! userId가 애매해서 고민했는데 감사합니다!

2022-08-28 07:50 UTC, coderclcl commented on src/main/java/org/almondiz/almondiz/user/UserService.java
> +    public User signup(UserRegisterDto userRegisterDto){
네넵 email과 트랜잭션 적용해볼게요!

2022-08-28 07:50 UTC, coderclcl commented on src/main/java/org/almondiz/almondiz/user/UserService.java
> +    public List<User> getAllUsers(){
엇 여기 제가 깜빡했나봐요 ㅋㅋㅋ 체크 감사합니다!

2022-08-28 14:46 UTC, yejipractice approved these changes
고생하셨어요 조금 수정할 부분이 있는데 제가 맡은 부분이기도 해서(회원가입쪽) 하고 다시 알려드릴게요 나머지 좋습니다! 고생하셨어요~

2022-08-28 14:47 UTC, merged