Feature/#17 글쓰기(Post) 구현
almondiz/almondiz-server pull request #26
Opened 2022-09-02 12:01 UTC by coderclcl

## 개요 ✋
글쓰기(Post) 구현

## 작업사항 🗒️
내용을 적어주세요.

## 변경로직 🛠️
- 위치별 post 조회는 거리 기준이 명확하지 않아서 구현을 미뤘습니다. 

## 논의 사항 
- PostService의 createPost에서 user id 가져오는 로직이 필요합니다. (JWT)  현재는 user id 를 임시로 1로 넣어뒀습니다. 
- API path에서 user id 를 제거하기로 했기 때문에 User controller에서 user id를 가져오는 로직 추가 후 코드를 변경해야 할 것 같습니다. (JWT) 
- PostController 에서 사용자별 post 조회 (/user/{userId}/posts) 구현시 userId를 path에서 빼는 방법이 떠오르지 않아서 논의가 필요합니다. 이 경우는 타인의 post를 조회하는 경우도 있어서 JWT로 해결이 불가능하고, 클라이언트에서 어쩔 수 없이 user id 값을 갖고 있게 될 것 같네요.. 
- Swagger 테스트가 잘 되지 않는데 이전에 통과됐던 user api 들도 다 테스트를 실패해서 충돌이 발생한 것 같습니다...! 무슨 문제인지 같이 찾아봐야할것같아요! 고쳐지면 다시 테스트해서 PR 라벨 바꿀게요!

2022-09-04 06:05 UTC, yejipractice requested changes
1. 매핑 유무 / 코드 컨벤션 의논
2. dto 적용 x 

이 정도면 될 것 같네요..?
고생하셨어요~~! 모두 확인했습니다 : )

2022-09-04 06:05 UTC, yejipractice commented on src/main/java/org/almondiz/almondiz/post/PostService.java
> +        // user id 임시값 - userId 가져오는 과정 추가 필요
여기도 반환이 Post 아닌가요?

2022-09-04 21:23 UTC, coderclcl commented on src/main/java/org/almondiz/almondiz/post/PostController.java
> +    @ApiOperation(value = "post 수정")
앗 혹시 tab size나 indent 문제 때문인가요?? 제가 이전에 4로 설정했었는데 어느샌가 다시 2로 돌아가있었네요.. 🤕 일단은 다시 맞춰뒀는데 혹시 다음에도 발견되면 다시 말씀 부탁드립니다..!

2022-09-04 21:23 UTC, coderclcl commented on src/main/java/org/almondiz/almondiz/post/entity/Post.java
> +    @Id
네네 이 부분은 User entity 참고해서 Identity로 맞춰뒀어요! 방금 조금 더 찾아봤는데 이 방식이 제일 간단하고 좋을 것 같다는 생각이 드네요! 일단은 IDENTITY로 가고 나중에 필요하면 바꾸는 게 어떨까요?? 
네 가지 방법에 대한 특징 정리 & 제 생각은 아래와 같습니다. 
- IDENTITY : 주로 AutoIncrement 기능 제공하는 DBMS( ex. MySQL ) 에서 사용
- SEQUENCE : MySQL은 Sequence 제공하지 않아서 이 방법은 적절하진 않을듯 
- TABLE : Key 생성 전용 Table 별도 생성 필요 (번거로울듯) 
- AUTO : DB에 따라 자동으로 IDENTITY, SEQUENCE, TABLE 전략 선택해주는 방식 (만약 TABLE 선택될 경우 번거로워질듯)

2022-09-04 21:23 UTC, coderclcl commented on src/main/java/org/almondiz/almondiz/postFile/entity/PostFile.java
> +
음 매핑이란게 FK와 PK 연결(1:1, 1:N 등) 을 의미하시는 거죠?? 저는 전체 테이블 어느정도 다 생성되고 나면 한번에 하는 게 좋을 것 같아서 일단 미뤄두긴 했습니다. 왜냐면 DB에서 관계 설정이 많아지면 api 테스트할 때 제약이 더 많을 것 같아서요..ㅎ  매핑하는 게 더 낫다면 수정해두겠습니다!

2022-09-04 21:23 UTC, coderclcl commented on src/main/java/org/almondiz/almondiz/store/entity/Store.java
> +
넵 수정해둘게요!

2022-09-05 02:25 UTC, yejipractice commented on src/main/java/org/almondiz/almondiz/post/PostController.java
> +    @ApiOperation(value = "post 수정")
사실 음.. 저도 확실하진 않은데 협업은 맞춰가는거니까요 😄  의논하면서 룰을 세워 나가는 것도 좋은 과정이 될 것 같습니다!  (탭 사이즈나 indent 포함) 어떤 변수 선언이 되었을 때 한 줄 빈칸으로 냅두고 다음 라인에 코드를 작성하고.. 이런 것들이 코드 리뷰, 가독성에 영향이 커서.. 이런 부분에 대해 한번 의논해보면 좋을 것 같아요 : )

2022-09-05 02:28 UTC, yejipractice commented on src/main/java/org/almondiz/almondiz/postFile/entity/PostFile.java
> +
아하 더미 데이터가 없어서 ㅠㅠ? 아... 그럼 음... 디비 하나를 연결해놓을까요 다음 스프린트에 바로? 어차피 지금까지 한 부분에 대한 api 문서를 드려야 할 것 같아서.. 이 방안이라면 해결 될까요?-?

2022-09-05 02:30 UTC, yejipractice commented on src/main/java/org/almondiz/almondiz/post/entity/Post.java
> +    private Clob title;
혹시 String 대신 Clob을 사용하신 이유가 기획 프로토타입을 보면 글 안에 이미지가 존재하기 때문일까요?

2022-09-05 03:18 UTC, yejipractice commented on src/main/java/org/almondiz/almondiz/post/entity/Post.java
> +    @Id
감사합니다 저도 IDENTITY가 맞을 것 같네요! 이걸로 모두 적용하겠습니다! 👍

2022-09-06 09:26 UTC, coderclcl commented on src/main/java/org/almondiz/almondiz/post/entity/Post.java
> +    private Clob title;
음 이 부분은 이전 코드 확인하신 것 같은데 최신 코드 보시면 String으로 변경되어 있습니다. 
처음에 Clob 으로 사용했던 이유는 [참고 링크](https://ksy93.tistory.com/entry/Jpa-Mysql-column-%EC%9E%90%EB%A3%8C%ED%98%95)에서 longtext 부분 참고해서 구현했습니다. 
String으로 하게 되면 255 제한이 있을 것 같은데 추후에 필요하면 전체적으로 조정할 필요가 있을 것 같아요!

2022-09-06 09:32 UTC, coderclcl commented on src/main/java/org/almondiz/almondiz/postFile/entity/PostFile.java
> +
네네 가능하다면 그것도 좋은 방법일 것 같아요! 일단은 모두 매핑해두겠습니다 😃

2022-09-06 14:49 UTC, coderclcl commented on src/main/java/org/almondiz/almondiz/post/entity/Post.java
> +    @Column(nullable = false)
매핑 완료했습니다!

2022-09-06 14:51 UTC, coderclcl commented on src/main/java/org/almondiz/almondiz/post/PostController.java
> +    @ApiOperation(value = "post 수정")
아하 다른 부분이었군요! 네넵 좋습니다! 이슈 만들어주시면 확인할게요~!

2022-09-06 14:51 UTC, coderclcl commented on src/main/java/org/almondiz/almondiz/store/entity/Store.java
> +
매핑 완료했습니다!

2022-09-06 15:42 UTC, coderclcl commented on src/main/java/org/almondiz/almondiz/postFile/entity/PostFile.java
> +
앗 자바에서는 Entity가 FK 대신 다른 객체를 포함하는군요.....??? 그래서 id로 한 이유를 물어보신 거였군요... 😭 ㅋㅋㅋㅋㅋㅋㅋㅋ ㅠㅠ 아 이제야 깨달았네요.. 다 고쳐야겠어요... 객체 지향은 다르군요..

2022-09-07 02:56 UTC, yejipractice commented on src/main/java/org/almondiz/almondiz/postFile/entity/PostFile.java
> +
넵! 객체로 매핑하게 되면 디비에도 반영되고 fk로는 객체의 id로 알아서 반영됩니다! : )

2022-09-07 03:03 UTC, yejipractice approved these changes
LGTM 👍 👍 고생하셨습니다 : )

2022-09-07 11:55 UTC, merged